---
- name: Install ghost as a docker container
  hosts: all
  become: True
  tasks:
  - name: Install virtualenv package
    apt:
      name: virtualenv
      update_cache: True
    become: True

  - name: Install docker into the specified (virtualenv)
    pip:
      name: docker
      virtualenv: ~/.venv/myvenv

  - name: Set python interpreter
    set_fact:
      ansible_python_interpreter: ~/.venv/myvenv/bin/python3

  - name: Run ghost as a Docker container
    docker_container:
      name: ghost
      image: ghost:5.33.2-alpine
      env:
        NODE_ENV: development
        url: "http://localhost:8080"
      ports:
      - "8080:2368"
