---
- name: Install and configure nginx
  hosts: all
  become: True
  vars:
    nginx_conf: >
      server {
          listen       80;
          server_name  example.com sub.example.com;

          location / {
              proxy_pass      http://127.0.0.1:8000;
          }
      }
  tasks:
    - name: Install nginx package
      apt:
        name: nginx
        update_cache: True
        cache_valid_time: 6000

    - name: Update nginx configuration
      copy:
        content: "{{ nginx_conf }}"
        dest: /etc/nginx/conf.d/example.com.conf
        owner: root
        group: root
        mode: '0644'
      notify: Reload nginx

    - name: Update nginx
      meta: flush_handlers
      notify: Reload nginx


  handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded